import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'tr_TR': {
          'merhaba dünya': 'Merhaba Dünya',
          'naber': 'Naber',
          'tıkla': 'Tıkla ',
          'ingilizce': 'İngilizce',
          'dil': 'Dil',
          'türkçe': 'Türkçe',
          'dildeğiştir': 'Türkçe',
          'oyun': 'Oyun',
          'puan denemeleri': 'Puan Denemeleri',
          'kütüphane': 'Kütüphane',
          'anasayfa': 'Anasayfa',
          'isa': 'İsa',
          'platon': 'Platon',
          'deneme': 'Deneme',
          'ağaç leyla': 'Ağaç Leyla',
          'bebiş': 'Bebiş',
          'Acemi': 'Acemi',
          'Çırak': 'Çırak',
          'Kalfa': 'Kalfa',
          'Usta': 'Usta',
          'Doktor': 'Doktor',
          'Prof': 'Prof',
          'Master': 'Master',
          'durum': 'durum',
          'final': 'Final',
          'ezgi': 'Ezgi',
          'talia': 'Talia',
          'profil resmi': 'Profil Fotoğrafı',
          'galeri': 'Galeri',
          'kamera': 'Kamera',
          'girisYazisi1': "Gezegen yok olmak üzere lütfen geminizi bulun!",
          'tebriklerSahne1':
              "Tebrikler geminiz aktive edildi! Quantum Tüneli Açıldı. İyi yolculuklar.",
          'sahne1sicrama': "Unic Evren'e Geçmek için Sıçramayı Başlat",
          "girisYazisiSahne2_1": "Uzaktaki mavi nokta yeni gezegenimiz Talia.",
          "girisYazisiSahne2_2":
              "Quantum sıçramasında tüm enerjimizi kaybettik. Enerji taşları toplamalıyız.",
          'sahne2sicrama':
              "Bir düşman gemisi tespit edildi. Onu yok etmeliyiz.",
          'dusmanTespitEdildi':
              "Düşman Bizi Tespit Etti. Silah Sistemleri Aktif. Ateş Et! ",
          'Deaktif': "Deaktif",
          'Doldur': "Doldur",
          'Evet': "Evet",
          'Hayır': "Hayır",
          'BüyükMercek': "Büyük Mercek",
          'GörüsAlanınıGenişletir': "Görüs Alanını Genişletir",
          'YeterliEnerjinizYok': "Yeterli Enerjiniz Yok!",
          'Silahlar': "Silahlar",
          'SınıfLazer': "3. Sınıf Lazer",
          'Enerji': "Enerji",
          'SilahlarAktiveEdilsin': "Silahlar Aktive Edilsin",
          'İnceleneceknesnebulunamadı': "İncelenecek nesne bulunamadı.",
          'Çıkış': "Çıkış",
          'İncelemebaşarılı': "İnceleme başarılı.",
          'Yağmacı': "Yağmacı:",
          'SınıfSavaşGemisi': "3. Sınıf Savaş Gemisi",
          'Olasılıklar': "Olasılıklar.",
          'Zafer': "Zafer olasılığı = %80",
          'Kaybetme': "Kaybetme olasılığı = %20.",
          'İncelemeRaporu': "İnceleme Raporu",
          'Düşmanıyoketveuzaklaş': "Düşmanı yok et ve uzaklaş.",
          'Öneri': "Öneri.",
          'Rapor': "Rapor",
          'Silah': "Silah",
          'Mercek': "Mercek",
          'Sahne3Bitti': "Düşman Yok Edildi. Ganimeti Toplayın.",
          'sahne4sicrama': "Geminizi Güçlendirmelisiniz!",
          'Üst': "Üst : ",
          'Sol': "Sol : ",
          'giriş yazısı':
              'Merhaba! Unic Otantic Eğitim Programı ile kaynak ekonomisine adım atıyorsunuz! '
                  'Unic Otantic Eğitim Programı sürdürülebilirlik, adalet ve şeffaflık ilkelerine dayalı '
                  'olarak tasarlanmış bir eğitim programıdır. Bu program hakkında bilgi sahibi olmak istiyorsanız '
                  'evet diyerek devam edebilirsiniz!',
          'ikinci yazı': ' Unic Otantic Eğitim Programı, küresel ekonomik sistemin sürdürülebilirliğini artırmak ve kaynakların '
              'daha adil bir şekilde paylaşılmasını sağlamak için tasarlanmıştır.\n\n'
              'Kaynak ekonomisi kavramını anlamanıza yardımcı olacak bir dizi eğitim materyalinden oluşmaktadır. Programımız, '
              'kaynakların kullanımı, dağıtımı ve yönetimi hakkında size bilgi verecek. Böylece, geleceğimizin sürdürülebilirliği '
              'için gerekli olan değişikliklere katkıda bulunabilirsiniz.\n\n'
              'Bu eğitim programına katılarak, kaynak ekonomisi konusunda bilinçlenerek dünya genelinde bir fark yaratabilirsiniz.\n\n'
              'Program hakkında daha fazla bilgi almak için evet diyebilirsiniz.',
          'üçüncü yazı bölüm bir': ' Unic topluluğu, kaynak ekonomisi, merkeziyetsizlik, evrensel değerler ve '
              'bilimsel tutum gibi konularda ortak fikirleri paylaşan insanlardan oluşuyor. Amacımız, '
              'insanlığın geleceği için önemli olan değerleri savunmak, geliştirmek ve korumaktır.\n\n'
              'Kaynak ekonomisi, tüm kaynakların sürdürülebilir şekilde kullanımı ve paylaşımını amaçlayan '
              'bir ekonomik modeldir. Bu model, doğal kaynakların etkili kullanımını, atıkların '
              'azaltılmasını ve yenilenebilir enerji kaynaklarının yaygınlaştırılmasını hedefler.\n\n '
              'Unic topluluğu olarak, kaynak ekonomisi prensiplerini savunuyoruz ve bu doğrultuda çalışmalar'
              ' yürütüyoruz.',
          'üçüncü yazı bölüm iki': 'Merkeziyetsizlik, herhangi bir merkezi otoritenin olmadığı sistemleri ifade eder. '
              'Bu sistemlerde, kararlar kullanıcılar tarafından alınır ve veriler merkezi bir sunucuda değil, blockchain'
              ' gibi dağıtık bir ağda saklanır. Merkeziyetsizlik, veri güvenliği ve kullanıcı haklarının korunması'
              ' açısından son derece önemlidir. Unic topluluğu olarak, merkeziyetsizlik fikrini benimseyerek, daha güvenli ve adil bir '
              'dünya için çalışıyoruz.\n\n'
              ' Online demokrasi, internet ve dijital teknolojilerin kullanımı '
              'ile gerçekleştirilen bir demokrasi türüdür. Bu demokrasi türünde, insanlar çevrimiçi '
              'platformlar üzerinden oy kullanabilir, geliştirmeler  hakkında fikirlerini '
              'belirtebilirler  ve diğer insanlar ile tartışabilirler. Online demokrasi, fiziksel '
              'olarak bir araya gelmek zorunda kalmadan, insanları bir araya getirerek katılımcılığı'
              ' artırır ve karar alma sürecini daha şeffaf ve erişilebilir hale getirir.',
          'üçüncü yazı bölüm üç': 'Unic topluluğu olarak, evrensel değerlere ve bilimsel tutuma da '
              'büyük önem veriyoruz. Toplumumuzda, insan hakları, hayvan hakları, çevre koruma, kadın erkek eşitliği '
              've LGBT hakları gibi değerleri savunuyoruz. Bilimin ışığında hareket ederek, doğru bilgiye dayalı '
              'kararlar alarak, insanlığın gelişimine katkıda bulunmayı hedefliyoruz.\n\n'
              'Eğer siz de Unic topluluğuna katılmak istiyorsanız, bu konularda net bir görüşünüzün olduğundan '
              'emin olmalısınız. Topluluğumuzun üye alımı belli kriterlere göre yapılır. Kaynak ekonomisi, '
              'merkeziyetsizlik, evrensel değerler ve bilimsel tutum konularında ortak fikirleri paylaşan '
              've bu ilkeleri benimseyen kişiler topluluğumuza katılabilirler.',
          'üçüncü yazı bölüm dört':
              'Unic topluluğu olarak, geleceğin daha adil ve sürdürülebilir bir'
                  ' dünya olacağına inanıyoruz. Siz de bu hedefe destek olmak isterseniz, bize katılın '
                  've bizimle birlikte çalışın.\n\n'
                  'Hazır mısınız!?',
          'kaynak ekonomisi nedir':
              'Kaynak ekonomisi, doğal kaynakların sürdürülebilir bir şekilde kullanımını teşvik eden bir ekonomik yaklaşımdır. '
                  'Bu yaklaşım, kaynakların tüketiminde, üretiminde ve atık yönetiminde daha verimli ve dikkatli bir şekilde '
                  'kullanılmasını amaçlar. Kaynakların sınırlı olduğu düşünüldüğünde, kaynak ekonomisi önemli bir kavram haline '
                  'gelir ve kaynakların gelecek nesillere de aktarılabilmesi için gereklidir. Kaynak ekonomisi yaklaşımı, çevresel '
                  'etkileri azaltmaya, iklim değişikliğiyle mücadele etmeye ve ekonomik kalkınmayı sürdürülebilir kılmaya yardımcı '
                  'olabilir.',
          'evet': 'Evet',
          'hayır': 'Hayır',
          'sarı': 'Sarı',
          'kırmızı': 'kırmızı',
          'mavi': 'mavi',
          'yeşil': 'yeşil',
          'turuncu': 'turuncu',
          'mor': 'mor',
          'denemeye git': 'denemeye git',
          // Yeni Eklenenler
          'akış': 'Akış',
          'profilim': 'Profilim',
          'mesajlar': 'Mesajlar',
          'bildirimler': 'Bildirimler',
          'arkadaşlar': 'Arkadaşlar',
          'takip_ettiklerim': 'Takip Ettiklerim',
          'sessize_alinanlar': 'Sessize Alınanlar',
          'engellenenler': 'Engellenenler',
          'ayarlar': 'Ayarlar',
          'oturumu_kapat': 'Oturumu Kapat',
          'isim_soyisim': 'İsim Soyisim',
          'kullanici_adi': 'Kullanıcı Adı (@)',
          'eposta': 'E-posta',
          'degisiklikleri_kaydet': 'Değişiklikleri Kaydet',
          'profili_gizle': 'Profili Gizle',
          'profil_gizli_mesaji': 'Profiliniz şu an gizli',
          'profil_acik_mesaji': 'Profiliniz herkese açık',
          'admin_paneli': 'Admin Paneli',
          'takip_et': 'Takip Et',
          'takibi_birak': 'Takibi Bırak',
          'mesaj_gonder': 'Mesaj Gönder',
          'takipci': 'Takipçi',
          'gonderi': 'Gönderi',
          'profil_duzenle': 'Profili Düzenle',
          'hata': 'Hata',
          'basarili': 'Başarılı',
          'fotograf_guncellendi': 'Profil fotoğrafı güncellendi.',
          'fotograf_yuklenemedi': 'Fotoğraf yüklenemedi: ',
          'isim_kullanici_bos': 'İsim ve kullanıcı adı boş olamaz.',
          'gecerli_kullanici_adi': 'Lütfen geçerli bir kullanıcı adı seçin.',
          'profil_kaydedildi': 'Profil bilgileriniz kaydedildi.',
          'cikis_yapilamadi': 'Çıkış yapılamadı.',
          'kullanici_adi_bos': 'Kullanıcı adı boş olamaz.',
          'kullanici_adi_kural':
              'Sadece küçük harf, rakam ve alt çizgi (3-20 krkt).',
          'kullanici_adi_alinmis': 'Bu kullanıcı adı zaten alınmış.',
          'kaydet': 'Kaydet',
          'iptal': 'İptal',
          'ceviriler_yuklendi': 'Çeviriler Yüklendi',
          'profil': 'Profil',
          'kullanici_bulunamadi': 'Kullanıcı bulunamadı.',
          'engellendi_mesaji': 'Bu kullanıcı sizi engelledi.',
          'engelledin_mesaji': 'Bu kullanıcıyı engellediniz.',
          'gonderiler': 'Gönderiler',
          'yorumlar': 'Yorumlar',
          'medya': 'Medya',
          'arkadas_ekle': 'Arkadaş Ekle',
          'istek_gonderildi': 'İstek Gönderildi',
          'istegi_onayla': 'İsteği Onayla',
          'arkadastan_cikar': 'Arkadaşlarımdan Çıkar',
          'sesi_ac': 'Sesi Aç',
          'sessize_al': 'Sessize Al',
          'engeli_kaldir': 'Engeli Kaldır',
          'engelle': 'Engelle',
          'henuz_bir_sey_yok': 'Henüz bir şey yok.',
          'medya_yok': 'Medya yok.',
          'bilgi': 'Bilgi',
          'takibi_biraktin': 'Takibi bıraktınız',
          'takip_etmeye_basladin': 'Takip etmeye başladınız',
          'ses_acildi': 'Kullanıcının sesi açıldı.',
          'sessize_alindi': 'Kullanıcı sessize alındı.',
          'engel_kaldirildi': 'Kullanıcının engeli kaldırıldı.',
          'kullanici_engellendi': 'Kullanıcı engellendi.',
          'arkadasi_cikar_baslik': 'Arkadaşı Çıkar',
          'arkadasi_cikar_icerik':
              'Bu kişiyi arkadaş listenizden çıkarmak istediğinize emin misiniz?',
          'cikar': 'Çıkar',
          'vazgec': 'Vazgeç',
          'takip': 'Takip',
          'gonderi_bulunamadi': 'Gönderi bulunamadı.',
          'gonderi_kisitli': 'Bu gönderi kısıtlanmıştır.',
          'kisitli_icerik_aciklama':
              'Engellediğiniz veya sizi engelleyen kullanıcıların içeriklerini göremezsiniz.',
          'yorum_yaz': 'Yorum yaz...',
          'arkadaslar_baslik': 'Arkadaşlar',
          'arkadaslari_baslik': 'Arkadaşları',
          'liste_gizli': 'Bu listeyi sadece arkadaşları görebilir.',
          'arkadas_yok': 'Henüz arkadaşın yok',
          'arkadas_alt': 'Arkadaş',
          'takipciler_baslik': 'Takipçiler',
          'takipceleri_baslik': 'Takipçileri',
          'takipci_yok': 'Henüz takipçin bulunmuyor',
          'seni_takip_ediyor': 'Seni takip ediyor',
          'takip_ettiklerim_baslik': 'Takip Ettiklerim',
          'takip_ettikleri_baslik': 'Takip Ettikleri',
          'kimseyi_takip_etmiyor': 'Henüz kimseyi takip etmiyorsun',
          'takip_ediliyor': 'Takip ediliyor',
          'takipten_cikarildi': 'Takipten çıkarıldı',
          'kesfet': 'Keşfet',
        },
        'en_US': {
          'giriş yazısı': 'Hello! You are taking a step towards resource economy with the Unique Authentic Education Program! '
              'The Unique Authentic Education Program is a training program designed based on sustainability, justice, and '
              'transparency principles.\n\n'
              'This program is designed to increase the sustainability of the global economic system and ensure a fairer'
              ' distribution of resources.  It consists of a series of educational materials that will help you understand '
              'the concept of resource economy. Our program will provide you with information on the use, distribution, and '
              'management of resources. \n\n'
              'Thus, you can contribute to the necessary changes for the sustainability of our future.  By participating in '
              'this education program, you can raise awareness about resource economy and make a difference globally.  \n\nYou can '
              'say yes to learn more about the program.',
          'kaynak ekonomisi nedir':
              'Kaynak ekonomisi, doğal kaynakların sürdürülebilir bir şekilde kullanımını teşvik eden bir ekonomik yaklaşımdır. '
                  'Bu yaklaşım, kaynakların tüketiminde, üretiminde ve atık yönetiminde daha verimli ve dikkatli bir şekilde '
                  'kullanılmasını amaçlar. Kaynakların sınırlı olduğu düşünüldüğünde, kaynak ekonomisi önemli bir kavram haline '
                  'gelir ve kaynakların gelecek nesillere de aktarılabilmesi için gereklidir. Kaynak ekonomisi yaklaşımı, çevresel '
                  'etkileri azaltmaya, iklim değişikliğiyle mücadele etmeye ve ekonomik kalkınmayı sürdürülebilir kılmaya yardımcı '
                  'olabilir.',
          'evet': 'yes',
          'sarı': 'yellow',
          'kırmızı': 'red',
          'mavi': 'blue',
          'yeşil': 'green',
          'turuncu': 'Orange',
          'mor': 'purple',
          'denemeye git': 'go to trial',
          'akış': 'Feed',
          'profilim': 'My Profile',
          'mesajlar': 'Messages',
          'bildirimler': 'Notifications',
          'arkadaşlar': 'Friends',
          'takip_ettiklerim': 'Following',
          'sessize_alinanlar': 'Muted Accounts',
          'engellenenler': 'Blocked Accounts',
          'ayarlar': 'Settings',
          'oturumu_kapat': 'Sign Out',
          'isim_soyisim': 'Name Surname',
          'kullanici_adi': 'Username (@)',
          'eposta': 'Email',
          'degisiklikleri_kaydet': 'Save Changes',
          'profili_gizle': 'Hide Profile',
          'profil_gizli_mesaji': 'Your profile is currently hidden',
          'profil_acik_mesaji': 'Your profile is public',
          'admin_paneli': 'Admin Panel',
          'takip_et': 'Follow',
          'takibi_birak': 'Unfollow',
          'mesaj_gonder': 'Send Message',
          'takipci': 'Followers',
          'gonderi': 'Posts',
          'profil_duzenle': 'Edit Profile',
          'hata': 'Error',
          'basarili': 'Success',
          'fotograf_guncellendi': 'Profile photo updated.',
          'fotograf_yuklenemedi': 'Photo could not be uploaded: ',
          'isim_kullanici_bos': 'Name and username cannot be empty.',
          'gecerli_kullanici_adi': 'Please choose a valid username.',
          'profil_kaydedildi': 'Profile information saved.',
          'cikis_yapilamadi': 'Could not sign out.',
          'kullanici_adi_bos': 'Username cannot be empty.',
          'kullanici_adi_kural':
              'Lowercase, numbers, underscore only (3-20 chars).',
          'kullanici_adi_alinmis': 'This username is already taken.',
          'kaydet': 'Save',
          'iptal': 'Cancel',
          'ceviriler_yuklendi': 'Translations Loaded',
          'tıkla': 'Click ',
          'dil': 'Language',
          'türkçe': 'Turkish',
          'profil': 'Profile',
          'kullanici_bulunamadi': 'User not found.',
          'engellendi_mesaji': 'This user has blocked you.',
          'engelledin_mesaji': 'You have blocked this user.',
          'gonderiler': 'Posts',
          'yorumlar': 'Comments',
          'medya': 'Media',
          'arkadas_ekle': 'Add Friend',
          'istek_gonderildi': 'Request Sent',
          'istegi_onayla': 'Confirm Request',
          'arkadastan_cikar': 'Remove Friend',
          'sesi_ac': 'Unmute',
          'sessize_al': 'Mute',
          'engeli_kaldir': 'Unblock',
          'engelle': 'Block',
          'henuz_bir_sey_yok': 'Nothing here yet.',
          'medya_yok': 'No media.',
          'bilgi': 'Info',
          'takibi_biraktin': 'Unfollowed',
          'takip_etmeye_basladin': 'Started following',
          'ses_acildi': 'User unmuted.',
          'sessize_alindi': 'User muted.',
          'engel_kaldirildi': 'User unblocked.',
          'kullanici_engellendi': 'User blocked.',
          'arkadasi_cikar_baslik': 'Remove Friend',
          'arkadasi_cikar_icerik':
              'Are you sure you want to remove this person from your friends list?',
          'cikar': 'Remove',
          'vazgec': 'Cancel',
          'takip': 'Following',
          'gonderi_bulunamadi': 'Post not found.',
          'gonderi_kisitli': 'This post is restricted.',
          'kisitli_icerik_aciklama':
              'You cannot see content from users you have blocked or who have blocked you.',
          'yorum_yaz': 'Write a comment...',
          'arkadaslar_baslik': 'Friends',
          'arkadaslari_baslik': 'Friends',
          'liste_gizli': 'Only friends can see this list.',
          'arkadas_yok': 'No friends yet',
          'arkadas_alt': 'Friend',
          'takipciler_baslik': 'Followers',
          'takipceleri_baslik': 'Followers',
          'takipci_yok': 'No followers yet',
          'seni_takip_ediyor': 'Follows you',
          'takip_ettiklerim_baslik': 'Following',
          'takip_ettikleri_baslik': 'Following',
          'kimseyi_takip_etmiyor': 'Not following anyone yet',
          'takip_ediliyor': 'Following',
          'takipten_cikarildi': 'Unfollowed',
          'kesfet': 'Discover',
        },
        'de_DE': {
          'giriş yazısı': 'Program wurde auf der Grundlage von Nachhaltigkeit, Gerechtigkeit und Transparenz entwickelt. Das '
              'Programm wurde entwickelt, um die Nachhaltigkeit des globalen Wirtschaftssystems zu erhöhen und eine gerechtere '
              'Verteilung der Ressourcen zu gewährleisten.  \n\n'
              'Das Programm besteht aus einer Reihe von Bildungsmaterialien, die Ihnen helfen, das Konzept der Ressourcenökonomie '
              'zu verstehen. Das Programm wird Sie über die Nutzung, Verteilung und Verwaltung von Ressourcen informieren. So können '
              'Sie dazu beitragen, die Veränderungen zu schaffen, die für die Nachhaltigkeit unserer Zukunft erforderlich sind. \n\n'
              'Durch die Teilnahme an diesem Bildungsprogramm können Sie sich über die Ressourcenökonomie bewusst werden und einen '
              'Unterschied in der Welt bewirken. \n\nWenn Sie weitere Informationen zu diesem Programm benötigen, '
              'können Sie mit "Ja" antworten. ',
          'kaynak ekonomisi nedir':
              'Kaynak ekonomisi, doğal kaynakların sürdürülebilir bir şekilde kullanımını teşvik eden bir ekonomik yaklaşımdır. '
                  'Bu yaklaşım, kaynakların tüketiminde, üretiminde ve atık yönetiminde daha verimli ve dikkatli bir şekilde '
                  'kullanılmasını amaçlar. Kaynakların sınırlı olduğu düşünüldüğünde, kaynak ekonomisi önemli bir kavram haline '
                  'gelir ve kaynakların gelecek nesillere de aktarılabilmesi için gereklidir. Kaynak ekonomisi yaklaşımı, çevresel '
                  'etkileri azaltmaya, iklim değişikliğiyle mücadele etmeye ve ekonomik kalkınmayı sürdürülebilir kılmaya yardımcı '
                  'olabilir.',
          'evet': 'ja',
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni':
              'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          'Swipe': "Wischen Sie nach oben",
          'akış': 'Feed',
          'profilim': 'Mein Profil',
          'mesajlar': 'Nachrichten',
          'bildirimler': 'Benachrichtigungen',
          'arkadaşlar': 'Freunde',
          'takip_ettiklerim': 'Gefolgt',
          'sessize_alinanlar': 'Stummgeschaltet',
          'engellenenler': 'Blockiert',
          'ayarlar': 'Einstellungen',
          'oturumu_kapat': 'Abmelden',
          'isim_soyisim': 'Name Nachname',
          'kullanici_adi': 'Benutzername (@)',
          'eposta': 'E-Mail',
          'degisiklikleri_kaydet': 'Änderungen speichern',
          'profili_gizle': 'Profil verbergen',
          'profil_gizli_mesaji': 'Ihr Profil ist derzeit verborgen',
          'profil_acik_mesaji': 'Ihr Profil ist öffentlich',
          'admin_paneli': 'Admin-Bereich',
          'takip_et': 'Folgen',
          'takibi_birak': 'Entfolgen',
          'mesaj_gonder': 'Nachricht senden',
          'takipci': 'Follower',
          'gonderi': 'Beiträge',
          'profil_duzenle': 'Profil bearbeiten',
          'hata': 'Fehler',
          'basarili': 'Erfolg',
          'fotograf_guncellendi': 'Profilbild aktualisiert.',
          'fotograf_yuklenemedi': 'Foto konnte nicht hochgeladen werden: ',
          'isim_kullanici_bos': 'Name und Benutzername dürfen nicht leer sein.',
          'gecerli_kullanici_adi':
              'Bitte wählen Sie einen gültigen Benutzernamen.',
          'profil_kaydedildi': 'Profilinformationen gespeichert.',
          'cikis_yapilamadi': 'Abmeldung nicht möglich.',
          'kullanici_adi_bos': 'Benutzername darf nicht leer sein.',
          'kullanici_adi_kural':
              'Nur Kleinbuchstaben, Zahlen und Unterstriche (3-20 Zeichen).',
          'kullanici_adi_alinmis': 'Dieser Benutzername ist bereits vergeben.',
          'kaydet': 'Speichern',
          'iptal': 'Abbrechen',
          'ceviriler_yuklendi': 'Übersetzungen geladen',
          'tıkla': 'Klicken ',
          'dil': 'Sprache',
          'türkçe': 'Türkisch',
          'profil': 'Profil',
          'kullanici_bulunamadi': 'Benutzer nicht gefunden.',
          'engellendi_mesaji': 'Dieser Benutzer hat dich blockiert.',
          'engelledin_mesaji': 'Du hast diesen Benutzer blockiert.',
          'gonderiler': 'Beiträge',
          'yorumlar': 'Kommentare',
          'medya': 'Medien',
          'arkadas_ekle': 'Freund hinzufügen',
          'istek_gonderildi': 'Anfrage gesendet',
          'istegi_onayla': 'Anfrage bestätigen',
          'arkadastan_cikar': 'Freund entfernen',
          'sesi_ac': 'Stummschaltung aufheben',
          'sessize_al': 'Stummschalten',
          'engeli_kaldir': 'Entblocken',
          'engelle': 'Blockieren',
          'henuz_bir_sey_yok': 'Noch nichts hier.',
          'medya_yok': 'Keine Medien.',
          'bilgi': 'Info',
          'takibi_biraktin': 'Entfolgt',
          'takip_etmeye_basladin': 'Gefolgt',
          'ses_acildi': 'Benutzer stummgeschaltet aufgehoben.',
          'sessize_alindi': 'Benutzer stummgeschaltet.',
          'engel_kaldirildi': 'Benutzer entblockt.',
          'kullanici_engellendi': 'Benutzer blockiert.',
          'arkadasi_cikar_baslik': 'Freund entfernen',
          'arkadasi_cikar_icerik':
              'Möchten Sie diese Person wirklich aus Ihrer Freundesliste entfernen?',
          'cikar': 'Entfernen',
          'vazgec': 'Abbrechen',
          'takip': 'Folgt',
          'gonderi_bulunamadi': 'Beitrag nicht gefunden.',
          'gonderi_kisitli': 'Dieser Beitrag ist eingeschränkt.',
          'kisitli_icerik_aciklama':
              'Sie können keine Inhalte von Benutzern sehen, die Sie blockiert haben oder die Sie blockiert haben.',
          'yorum_yaz': 'Kommentar schreiben...',
          'arkadaslar_baslik': 'Freunde',
          'arkadaslari_baslik': 'Freunde',
          'liste_gizli': 'Nur Freunde können diese Liste sehen.',
          'arkadas_yok': 'Noch keine Freunde',
          'arkadas_alt': 'Freund',
          'takipciler_baslik': 'Follower',
          'takipceleri_baslik': 'Follower',
          'takipci_yok': 'Noch keine Follower',
          'seni_takip_ediyor': 'Folgt dir',
          'takip_ettiklerim_baslik': 'Ich folge',
          'takip_ettikleri_baslik': 'Folgt',
          'kimseyi_takip_etmiyor': 'Folgt noch niemandem',
          'takip_ediliyor': 'Folgt',
          'takipten_cikarildi': 'Entfolgt',
          'kesfet': 'Entdecken',
        },
        'en_EN': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_AU': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_CA': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_IN': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_SG': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_ZA': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'de_DE': {
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni':
              'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben",
        },
        'de_LI': {
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni':
              'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Gelb',
          'kirmizi': 'Rot',
          'mavi': 'Blau',
          'yesil': 'Grün',
          'mor': 'Lila',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben"
        },
        'de_LU': {
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni':
              'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Gelb',
          'kirmizi': 'Rot',
          'mavi': 'Blau',
          'yesil': 'Grün',
          'mor': 'Lila',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben"
        },
        'de_AT': {
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni':
              'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Gelb',
          'kirmizi': 'Rot',
          'mavi': 'Blau',
          'yesil': 'Grün',
          'mor': 'Lila',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben"
        },
        'nl_NL': {
          'puan': 'Scoren: ',
          'oyna': 'B E G I N',
          'zamanbitti': 'Tijd is Verstreken',
          'reklamMetni':
              'Verdien +11 seconden door advertenties met beloning te bekijken.',
          'reklamButonu': 'Bekijk Advertenties',
          'tekrarOyna': 'Speel Opnieuw',
          'dildeğiştir': 'Dutch',
          'oyunuKapat': 'Sluit het spel',
          'oyunaDön': 'Terug naar Spel',
          'sari': 'Geel',
          'kirmizi': 'Rood',
          'mavi': 'Blauw',
          'yesil': 'Groen',
          'mor': 'Paars',
          "Kazandınız": "Je hebt gewonnen",
          "Speed": "Snelheid",
          "Swipe": "Omhoog vegen"
        },
        'nl_BE': {
          'puan': 'Scoren: ',
          'oyna': 'B E G I N',
          'zamanbitti': 'Tijd is Verstreken',
          'reklamMetni':
              'Verdien +11 seconden door advertenties met beloning te bekijken.',
          'reklamButonu': 'Bekijk Advertenties',
          'tekrarOyna': 'Speel Opnieuw',
          'dildeğiştir': 'Dutch',
          'oyunuKapat': 'Sluit het spel',
          'oyunaDön': 'Terug naar Spel',
          'sari': 'Geel',
          'kirmizi': 'Rood',
          'mavi': 'Blauw',
          'yesil': 'Groen',
          'mor': 'Paars',
          "Kazandınız": "Je hebt gewonnen",
          "Speed": "Snelheid",
          "Swipe": "Omhoog vegen"
        },
        'nn_NO': {
          'puan': 'Pens: ',
          'oyna': 'Skuespill',
          'zamanbitti': 'Tidsavbrudd',
          'reklamMetni': 'Tjen +11 sekunder ved å se belønningsannonser.',
          'reklamButonu': 'Vis annonser',
          'tekrarOyna': 'Spill på nytt',
          'dildeğiştir': 'Norway',
          'oyunuKapat': 'Lukk spillet',
          'oyunaDön': 'Tilbake til spillet',
          'sari': 'Gul',
          'kirmizi': 'Rød',
          'mavi': 'Blå',
          'yesil': 'Grønn',
          'mor': 'Lilla',
          "Kazandınız": "Du vant",
          "Speed": "Fart",
          "Swipe": "Sveip opp"
        },
        'fr_FR': {
          'puan': 'Scoren: ',
          'oyna': 'J O U E R',
          'zamanbitti': 'Le Temps Est écoulé',
          'reklamMetni':
              'Gagnez +11 secondes en regardant des publicités avec récompense.',
          'reklamButonu': 'Voir les annonces',
          'tekrarOyna': 'Rejouer',
          'dildeğiştir': 'French',
          'oyunuKapat': 'Fermer le jeu',
          'oyunaDön': 'Retour au jeu',
          'sari': 'Jaune',
          'kirmizi': 'Rouge',
          'mavi': 'Bleu',
          'yesil': 'Vert',
          'mor': 'Pourpre',
          "Kazandınız": "Vous avez gagné",
          "Speed": "Vitesse",
          "Swipe": "Balayez vers le haut",
          'akış': 'Flux',
          'profilim': 'Mon Profil',
          'mesajlar': 'Messages',
          'bildirimler': 'Notifications',
          'arkadaşlar': 'Amis',
          'takip_ettiklerim': 'Abonnements',
          'sessize_alinanlar': 'Comptes muets',
          'engellenenler': 'Comptes bloqués',
          'ayarlar': 'Paramètres',
          'oturumu_kapat': 'Se déconnecter',
          'isim_soyisim': 'Prénom Nom',
          'kullanici_adi': 'Nom d\'utilisateur (@)',
          'eposta': 'E-mail',
          'degisiklikleri_kaydet': 'Enregistrer les modifications',
          'profili_gizle': 'Masquer le profil',
          'profil_gizli_mesaji': 'Votre profil est actuellement masqué',
          'profil_acik_mesaji': 'Votre profil est public',
          'admin_paneli': 'Panneau d\'administration',
          'takip_et': 'Suivre',
          'takibi_birak': 'Ne plus suivre',
          'mesaj_gonder': 'Envoyer un message',
          'takipci': 'Abonnés',
          'gonderi': 'Publications',
          'profil_duzenle': 'Modifier le profil',
          'hata': 'Erreur',
          'basarili': 'Succès',
          'fotograf_guncellendi': 'Photo de profil mise à jour.',
          'fotograf_yuklenemedi': 'La photo n\'a pas pu être téléchargée : ',
          'isim_kullanici_bos':
              'Le nom et le nom d\'utilisateur ne peuvent pas être vides.',
          'gecerli_kullanici_adi':
              'Veuillez choisir un nom d\'utilisateur valide.',
          'profil_kaydedildi': 'Informations de profil enregistrées.',
          'cikis_yapilamadi': 'Impossible de se déconnecter.',
          'kullanici_adi_bos': 'Le nom d\'utilisateur ne peut pas être vide.',
          'kullanici_adi_kural':
              'Minuscules, chiffres et traits de soulignement uniquement (3-20 car.).',
          'kullanici_adi_alinmis': 'Ce nom d\'utilisateur est déjà pris.',
          'kaydet': 'Enregistrer',
          'iptal': 'Annuler',
          'ceviriler_yuklendi': 'Traductions chargées',
          'tıkla': 'Cliquer ',
          'dil': 'Langue',
          'türkçe': 'Turc',
          'profil': 'Profil',
          'kullanici_bulunamadi': 'Utilisateur non trouvé.',
          'engellendi_mesaji': 'Cet utilisateur vous a bloqué.',
          'engelledin_mesaji': 'Vous avez bloqué cet utilisateur.',
          'gonderiler': 'Publications',
          'yorumlar': 'Commentaires',
          'medya': 'Médias',
          'arkadas_ekle': 'Ajouter un ami',
          'istek_gonderildi': 'Demande envoyée',
          'istegi_onayla': 'Confirmer la demande',
          'arkadastan_cikar': 'Retirer un ami',
          'sesi_ac': 'Rétablir le son',
          'sessize_al': 'Mettre en sourdine',
          'engeli_kaldir': 'Débloquer',
          'engelle': 'Bloquer',
          'henuz_bir_sey_yok': 'Rien ici pour le moment.',
          'medya_yok': 'Pas de média.',
          'bilgi': 'Info',
          'takibi_biraktin': 'Ne suit plus',
          'takip_etmeye_basladin': 'A commencé à suivre',
          'ses_acildi': 'Utilisateur rétabli.',
          'sessize_alindi': 'Utilisateur mis en sourdine.',
          'engel_kaldirildi': 'Utilisateur débloqué.',
          'kullanici_engellendi': 'Utilisateur bloqué.',
          'arkadasi_cikar_baslik': 'Retirer un ami',
          'arkadasi_cikar_icerik':
              'Voulez-vous vraiment retirer cette personne de votre liste d\'amis ?',
          'cikar': 'Retirer',
          'vazgec': 'Annuler',
          'takip': 'Abonnements',
          'gonderi_bulunamadi': 'Publication introuvable.',
          'gonderi_kisitli': 'Cette publication est restreinte.',
          'kisitli_icerik_aciklama':
              'Vous ne pouvez pas voir le contenu des utilisateurs que vous avez bloqués ou qui vous ont bloqué.',
          'yorum_yaz': 'Écrire un commentaire...',
          'arkadaslar_baslik': 'Amis',
          'arkadaslari_baslik': 'Amis',
          'liste_gizli': 'Seuls les amis peuvent voir cette liste.',
          'arkadas_yok': 'Pas encore d\'amis',
          'arkadas_alt': 'Ami',
          'takipciler_baslik': 'Abonnés',
          'takipceleri_baslik': 'Abonnés',
          'takipci_yok': 'Pas encore d\'abonnés',
          'seni_takip_ediyor': 'Vous suit',
          'takip_ettiklerim_baslik': 'Abonnements',
          'takip_ettikleri_baslik': 'Abonnements',
          'kimseyi_takip_etmiyor': 'Ne suit personne pour le moment',
          'takip_ediliyor': 'Suit',
          'takipten_cikarildi': 'Ne suit plus',
          'kesfet': 'Découvrir',
        },
        'fr_LU': {
          'puan': 'Scoren: ',
          'oyna': 'J O U E R',
          'zamanbitti': 'Le Temps Est écoulé',
          'reklamMetni':
              'Gagnez +11 secondes en regardant des publicités avec récompense.',
          'reklamButonu': 'Voir les annonces',
          'tekrarOyna': 'Rejouer',
          'dildeğiştir': 'French',
          'oyunuKapat': 'Fermer le jeu',
          'oyunaDön': 'Retour au jeu',
          'sari': 'Jaune',
          'kirmizi': 'Rouge',
          'mavi': 'Bleu',
          'yesil': 'Vert',
          'mor': 'Pourpre',
          "Kazandınız": "Vous avez gagné",
          "Speed": "Vitesse",
          "Swipe": "Balayez vers le haut",
        },
        'fr_MC': {
          'puan': 'Scoren: ',
          'oyna': 'J O U E R',
          'zamanbitti': 'Le Temps Est écoulé',
          'reklamMetni':
              'Gagnez +11 secondes en regardant des publicités avec récompense.',
          'reklamButonu': 'Voir les annonces',
          'tekrarOyna': 'Rejouer',
          'dildeğiştir': 'French',
          'oyunuKapat': 'Fermer le jeu',
          'oyunaDön': 'Retour au jeu',
          'sari': 'Jaune',
          'kirmizi': 'Rouge',
          'mavi': 'Bleu',
          'yesil': 'Vert',
          'mor': 'Pourpre',
          "Kazandınız": "Vous avez gagné",
          "Speed": "Vitesse",
          "Swipe": "Balayez vers le haut",
        },
        'fr_CH': {
          'puan': 'Scoren: ',
          'oyna': 'J O U E R',
          'zamanbitti': 'Le Temps Est écoulé',
          'reklamMetni':
              'Gagnez +11 secondes en regardant des publicités avec récompense.',
          'reklamButonu': 'Voir les annonces',
          'tekrarOyna': 'Rejouer',
          'dildeğiştir': 'French',
          'oyunuKapat': 'Fermer le jeu',
          'oyunaDön': 'Retour au jeu',
          'sari': 'Jaune',
          'kirmizi': 'Rouge',
          'mavi': 'Bleu',
          'yesil': 'Vert',
          'mor': 'Pourpre',
          "Kazandınız": "Vous avez gagné",
          "Speed": "Vitesse",
          "Swipe": "Balayez vers le haut",
        },
        'ru_RU': {
          'puan': 'точка: ',
          'oyna': 'Начинать',
          'zamanbitti': 'время истекло',
          'reklamMetni':
              'Заработайте +11 секунд, просматривая рекламу с вознаграждением.',
          'reklamButonu': 'смотреть рекламу',
          'tekrarOyna': 'играть снова',
          'dildeğiştir': 'Russian',
          'oyunuKapat': 'Закрыть игру',
          'oyunaDön': 'Вернуться к игре',
          'sari': 'Жёлтый',
          'kirmizi': 'Красный',
          'mavi': 'Синий',
          'yesil': 'Зеленый',
          'mor': 'Пурпурный',
          "Kazandınız": "Вы выиграли",
          "Speed": "Скорость",
          "Swipe": "Проведите пальцем вверх",
        },
        'es_ES': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_VE': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_UY': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_PE': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_PR': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_PY': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_MX': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_HN': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_GT': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_SV': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_EC': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_DO': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_CR': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_CO': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_CL': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_BO': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_AR': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'ja_JP': {
          'puan': 'スコア : ',
          'oyna': '始める',
          'zamanbitti': 'たんま',
          'reklamMetni': 'リワード広告を表示すると +11 秒増加します。',
          'reklamButonu': 'お知らせを表示する',
          'tekrarOyna': 'もう一度再生',
          'dildeğiştir': 'Japanese',
          'oyunuKapat': 'ゲームを閉じる',
          'oyunaDön': 'ゲームに戻る',
          'sari': '黄色',
          'kirmizi': '赤い',
          'mavi': '青い',
          'yesil': '緑',
          'mor': '紫',
          "Kazandınız": "あなたが勝った",
          "Speed": "速度",
          "Swipe": "上にスワイプ",
        },
      };
}
