import 'package:get/get.dart';

class Messages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'tr_TR': {
          'merhaba dünya': 'Merhaba Dünya',
          'naber': 'Naber',
          'tıkla': 'Tıkla ',
          'ingilizce': 'İngilizce',
          'dil': 'Dil',
          'türkçe': 'Türkçe',
          'dildeğiştir': 'Türkçe',
          'oyun': 'Oyun',
          'puan denemeleri': 'Puan Denemeleri',
          'kütüphane': 'Kütüphane',
          'anasayfa': 'Anasayfa',
          'isa': 'İsa',
          'platon': 'Platon',
          'deneme': 'Deneme',
          'ağaç leyla': 'Ağaç Leyla',
          'bebiş': 'Bebiş',
          'Acemi': 'Acemi',
          'Çırak': 'Çırak',
          'Kalfa': 'Kalfa',
          'Usta': 'Usta',
          'Doktor': 'Doktor',
          'Prof': 'Prof',
          'Master': 'Master',
          'durum': 'durum',
          'final': 'Final',
          'ezgi': 'Ezgi',
          'talia': 'Talia',
          'profil resmi': 'Profil Fotoğrafı',
          'galeri': 'Galeri',
          'kamera': 'Kamera',
          'girisYazisi1': "Gezegen yok olmak üzere lütfen geminizi bulun!",
          'tebriklerSahne1': "Tebrikler geminiz aktive edildi! Quantum Tüneli Açıldı. İyi yolculuklar.",
          'sahne1sicrama': "Unic Evren'e Geçmek için Sıçramayı Başlat",
          "girisYazisiSahne2_1": "Uzaktaki mavi nokta yeni gezegenimiz Talia.",
          "girisYazisiSahne2_2": "Quantum sıçramasında tüm enerjimizi kaybettik. Enerji taşları toplamalıyız.",
          'sahne2sicrama': "Bir düşman gemisi tespit edildi. Onu yok etmeliyiz.",
          'dusmanTespitEdildi': "Düşman Bizi Tespit Etti. Silah Sistemleri Aktif. Ateş Et! ",
          'Deaktif': "Deaktif",
          'Doldur': "Doldur",
          'Evet': "Evet",
          'Hayır': "Hayır",
          'BüyükMercek': "Büyük Mercek",
          'GörüsAlanınıGenişletir': "Görüs Alanını Genişletir",
          'YeterliEnerjinizYok': "Yeterli Enerjiniz Yok!",
          'Silahlar': "Silahlar",
          'SınıfLazer': "3. Sınıf Lazer",
          'Enerji': "Enerji",
          'SilahlarAktiveEdilsin': "Silahlar Aktive Edilsin",
          'İnceleneceknesnebulunamadı': "İncelenecek nesne bulunamadı.",
          'Çıkış': "Çıkış",
          'İncelemebaşarılı': "İnceleme başarılı.",
          'Yağmacı': "Yağmacı:",
          'SınıfSavaşGemisi': "3. Sınıf Savaş Gemisi",
          'Olasılıklar': "Olasılıklar.",
          'Zafer': "Zafer olasılığı = %80",
          'Kaybetme': "Kaybetme olasılığı = %20.",
          'İncelemeRaporu': "İnceleme Raporu",
          'Düşmanıyoketveuzaklaş': "Düşmanı yok et ve uzaklaş.",
          'Öneri': "Öneri.",
          'Rapor': "Rapor",
          'Silah': "Silah",
          'Mercek': "Mercek",
          'Sahne3Bitti': "Düşman Yok Edildi. Ganimeti Toplayın.",
          'sahne4sicrama': "Geminizi Güçlendirmelisiniz!",
          'Üst': "Üst : ",
          'Sol': "Sol : ",
          'giriş yazısı': 'Merhaba! Unic Otantic Eğitim Programı ile kaynak ekonomisine adım atıyorsunuz! '
              'Unic Otantic Eğitim Programı sürdürülebilirlik, adalet ve şeffaflık ilkelerine dayalı '
              'olarak tasarlanmış bir eğitim programıdır. Bu program hakkında bilgi sahibi olmak istiyorsanız '
              'evet diyerek devam edebilirsiniz!',
          'ikinci yazı': ' Unic Otantic Eğitim Programı, küresel ekonomik sistemin sürdürülebilirliğini artırmak ve kaynakların '
              'daha adil bir şekilde paylaşılmasını sağlamak için tasarlanmıştır.\n\n'
              'Kaynak ekonomisi kavramını anlamanıza yardımcı olacak bir dizi eğitim materyalinden oluşmaktadır. Programımız, '
              'kaynakların kullanımı, dağıtımı ve yönetimi hakkında size bilgi verecek. Böylece, geleceğimizin sürdürülebilirliği '
              'için gerekli olan değişikliklere katkıda bulunabilirsiniz.\n\n'
              'Bu eğitim programına katılarak, kaynak ekonomisi konusunda bilinçlenerek dünya genelinde bir fark yaratabilirsiniz.\n\n'
              'Program hakkında daha fazla bilgi almak için evet diyebilirsiniz.',
          'üçüncü yazı bölüm bir': ' Unic topluluğu, kaynak ekonomisi, merkeziyetsizlik, evrensel değerler ve '
              'bilimsel tutum gibi konularda ortak fikirleri paylaşan insanlardan oluşuyor. Amacımız, '
              'insanlığın geleceği için önemli olan değerleri savunmak, geliştirmek ve korumaktır.\n\n'
              'Kaynak ekonomisi, tüm kaynakların sürdürülebilir şekilde kullanımı ve paylaşımını amaçlayan '
              'bir ekonomik modeldir. Bu model, doğal kaynakların etkili kullanımını, atıkların '
              'azaltılmasını ve yenilenebilir enerji kaynaklarının yaygınlaştırılmasını hedefler.\n\n '
              'Unic topluluğu olarak, kaynak ekonomisi prensiplerini savunuyoruz ve bu doğrultuda çalışmalar'
              ' yürütüyoruz.',
          'üçüncü yazı bölüm iki': 'Merkeziyetsizlik, herhangi bir merkezi otoritenin olmadığı sistemleri ifade eder. '
              'Bu sistemlerde, kararlar kullanıcılar tarafından alınır ve veriler merkezi bir sunucuda değil, blockchain'
              ' gibi dağıtık bir ağda saklanır. Merkeziyetsizlik, veri güvenliği ve kullanıcı haklarının korunması'
              ' açısından son derece önemlidir. Unic topluluğu olarak, merkeziyetsizlik fikrini benimseyerek, daha güvenli ve adil bir '
              'dünya için çalışıyoruz.\n\n'
              ' Online demokrasi, internet ve dijital teknolojilerin kullanımı '
              'ile gerçekleştirilen bir demokrasi türüdür. Bu demokrasi türünde, insanlar çevrimiçi '
              'platformlar üzerinden oy kullanabilir, geliştirmeler  hakkında fikirlerini '
              'belirtebilirler  ve diğer insanlar ile tartışabilirler. Online demokrasi, fiziksel '
              'olarak bir araya gelmek zorunda kalmadan, insanları bir araya getirerek katılımcılığı'
              ' artırır ve karar alma sürecini daha şeffaf ve erişilebilir hale getirir.',
          'üçüncü yazı bölüm üç': 'Unic topluluğu olarak, evrensel değerlere ve bilimsel tutuma da '
              'büyük önem veriyoruz. Toplumumuzda, insan hakları, hayvan hakları, çevre koruma, kadın erkek eşitliği '
              've LGBT hakları gibi değerleri savunuyoruz. Bilimin ışığında hareket ederek, doğru bilgiye dayalı '
              'kararlar alarak, insanlığın gelişimine katkıda bulunmayı hedefliyoruz.\n\n'
              'Eğer siz de Unic topluluğuna katılmak istiyorsanız, bu konularda net bir görüşünüzün olduğundan '
              'emin olmalısınız. Topluluğumuzun üye alımı belli kriterlere göre yapılır. Kaynak ekonomisi, '
              'merkeziyetsizlik, evrensel değerler ve bilimsel tutum konularında ortak fikirleri paylaşan '
              've bu ilkeleri benimseyen kişiler topluluğumuza katılabilirler.',
          'üçüncü yazı bölüm dört': 'Unic topluluğu olarak, geleceğin daha adil ve sürdürülebilir bir'
              ' dünya olacağına inanıyoruz. Siz de bu hedefe destek olmak isterseniz, bize katılın '
              've bizimle birlikte çalışın.\n\n'
              'Hazır mısınız!?',
          'kaynak ekonomisi nedir':
              'Kaynak ekonomisi, doğal kaynakların sürdürülebilir bir şekilde kullanımını teşvik eden bir ekonomik yaklaşımdır. '
                  'Bu yaklaşım, kaynakların tüketiminde, üretiminde ve atık yönetiminde daha verimli ve dikkatli bir şekilde '
                  'kullanılmasını amaçlar. Kaynakların sınırlı olduğu düşünüldüğünde, kaynak ekonomisi önemli bir kavram haline '
                  'gelir ve kaynakların gelecek nesillere de aktarılabilmesi için gereklidir. Kaynak ekonomisi yaklaşımı, çevresel '
                  'etkileri azaltmaya, iklim değişikliğiyle mücadele etmeye ve ekonomik kalkınmayı sürdürülebilir kılmaya yardımcı '
                  'olabilir.',
          'evet': 'Evet',
          'hayır': 'Hayır',
          'sarı': 'Sarı',
          'kırmızı': 'kırmızı',
          'mavi': 'mavi',
          'yeşil': 'yeşil',
          'turuncu': 'turuncu',
          'mor': 'mor',
          'denemeye git': 'denemeye git',
        },
        'en_US': {
          'giriş yazısı': 'Hello! You are taking a step towards resource economy with the Unique Authentic Education Program! '
              'The Unique Authentic Education Program is a training program designed based on sustainability, justice, and '
              'transparency principles.\n\n'
              'This program is designed to increase the sustainability of the global economic system and ensure a fairer'
              ' distribution of resources.  It consists of a series of educational materials that will help you understand '
              'the concept of resource economy. Our program will provide you with information on the use, distribution, and '
              'management of resources. \n\n'
              'Thus, you can contribute to the necessary changes for the sustainability of our future.  By participating in '
              'this education program, you can raise awareness about resource economy and make a difference globally.  \n\nYou can '
              'say yes to learn more about the program.',
          'kaynak ekonomisi nedir':
              'Kaynak ekonomisi, doğal kaynakların sürdürülebilir bir şekilde kullanımını teşvik eden bir ekonomik yaklaşımdır. '
                  'Bu yaklaşım, kaynakların tüketiminde, üretiminde ve atık yönetiminde daha verimli ve dikkatli bir şekilde '
                  'kullanılmasını amaçlar. Kaynakların sınırlı olduğu düşünüldüğünde, kaynak ekonomisi önemli bir kavram haline '
                  'gelir ve kaynakların gelecek nesillere de aktarılabilmesi için gereklidir. Kaynak ekonomisi yaklaşımı, çevresel '
                  'etkileri azaltmaya, iklim değişikliğiyle mücadele etmeye ve ekonomik kalkınmayı sürdürülebilir kılmaya yardımcı '
                  'olabilir.',
          'evet': 'yes',
          'sarı': 'yellow',
          'kırmızı': 'red',
          'mavi': 'blue',
          'yeşil': 'green',
          'turuncu': 'Orange',
          'mor': 'purple',
          'denemeye git': 'go to trial',
        },
        'de_DE': {
          'giriş yazısı': 'Program wurde auf der Grundlage von Nachhaltigkeit, Gerechtigkeit und Transparenz entwickelt. Das '
              'Programm wurde entwickelt, um die Nachhaltigkeit des globalen Wirtschaftssystems zu erhöhen und eine gerechtere '
              'Verteilung der Ressourcen zu gewährleisten.  \n\n'
              'Das Programm besteht aus einer Reihe von Bildungsmaterialien, die Ihnen helfen, das Konzept der Ressourcenökonomie '
              'zu verstehen. Das Programm wird Sie über die Nutzung, Verteilung und Verwaltung von Ressourcen informieren. So können '
              'Sie dazu beitragen, die Veränderungen zu schaffen, die für die Nachhaltigkeit unserer Zukunft erforderlich sind. \n\n'
              'Durch die Teilnahme an diesem Bildungsprogramm können Sie sich über die Ressourcenökonomie bewusst werden und einen '
              'Unterschied in der Welt bewirken. \n\nWenn Sie weitere Informationen zu diesem Programm benötigen, '
              'können Sie mit "Ja" antworten. ',
          'kaynak ekonomisi nedir':
              'Kaynak ekonomisi, doğal kaynakların sürdürülebilir bir şekilde kullanımını teşvik eden bir ekonomik yaklaşımdır. '
                  'Bu yaklaşım, kaynakların tüketiminde, üretiminde ve atık yönetiminde daha verimli ve dikkatli bir şekilde '
                  'kullanılmasını amaçlar. Kaynakların sınırlı olduğu düşünüldüğünde, kaynak ekonomisi önemli bir kavram haline '
                  'gelir ve kaynakların gelecek nesillere de aktarılabilmesi için gereklidir. Kaynak ekonomisi yaklaşımı, çevresel '
                  'etkileri azaltmaya, iklim değişikliğiyle mücadele etmeye ve ekonomik kalkınmayı sürdürülebilir kılmaya yardımcı '
                  'olabilir.',
          'evet': 'ja',
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni': 'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben",
        },
        'en_EN': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_AU': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_CA': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_IN': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_SG': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'en_ZA': {
          'puan': 'Score: ',
          'oyna': 'P L A Y',
          'zamanbitti': 'Time is Over',
          'reklamMetni': 'Earn +11 seconds by \nwatching Rewarded Ads.',
          'reklamButonu': 'Watch Ads',
          'tekrarOyna': 'Play Again',
          'dildeğiştir': 'English',
          'oyunuKapat': 'Exit the game',
          'oyunaDön': 'Back to Game',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "You Won",
          "Speed": "Speed",
          "Swipe": "Swipe up",
        },
        'de_DE': {
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni': 'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Yellow',
          'kirmizi': 'Red',
          'mavi': 'Blue',
          'yesil': 'Green',
          'mor': 'Purple',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben",
        },
        'de_LI': {
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni': 'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Gelb',
          'kirmizi': 'Rot',
          'mavi': 'Blau',
          'yesil': 'Grün',
          'mor': 'Lila',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben"
        },
        'de_LU': {
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni': 'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Gelb',
          'kirmizi': 'Rot',
          'mavi': 'Blau',
          'yesil': 'Grün',
          'mor': 'Lila',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben"
        },
        'de_AT': {
          'puan': 'Punktzahl: ',
          'oyna': 'S T A R T',
          'zamanbitti': 'ZEIT UM',
          'reklamMetni': 'Verdienen Sie +11 Sekunden, indem Sie Rewarded Ads ansehen.',
          'reklamButonu': 'Anzeigen Ansehen',
          'tekrarOyna': 'Nochmal Abspielen',
          'dildeğiştir': 'German',
          'oyunuKapat': 'Schließe das Spiel',
          'oyunaDön': 'Zurück zum Spiel',
          'sari': 'Gelb',
          'kirmizi': 'Rot',
          'mavi': 'Blau',
          'yesil': 'Grün',
          'mor': 'Lila',
          "Kazandınız": "Sie haben gewonnen",
          "Speed": "Geschwindigkeit",
          "Swipe": "Wischen Sie nach oben"
        },
        'nl_NL': {
          'puan': 'Scoren: ',
          'oyna': 'B E G I N',
          'zamanbitti': 'Tijd is Verstreken',
          'reklamMetni': 'Verdien +11 seconden door advertenties met beloning te bekijken.',
          'reklamButonu': 'Bekijk Advertenties',
          'tekrarOyna': 'Speel Opnieuw',
          'dildeğiştir': 'Dutch',
          'oyunuKapat': 'Sluit het spel',
          'oyunaDön': 'Terug naar Spel',
          'sari': 'Geel',
          'kirmizi': 'Rood',
          'mavi': 'Blauw',
          'yesil': 'Groen',
          'mor': 'Paars',
          "Kazandınız": "Je hebt gewonnen",
          "Speed": "Snelheid",
          "Swipe": "Omhoog vegen"
        },
        'nl_BE': {
          'puan': 'Scoren: ',
          'oyna': 'B E G I N',
          'zamanbitti': 'Tijd is Verstreken',
          'reklamMetni': 'Verdien +11 seconden door advertenties met beloning te bekijken.',
          'reklamButonu': 'Bekijk Advertenties',
          'tekrarOyna': 'Speel Opnieuw',
          'dildeğiştir': 'Dutch',
          'oyunuKapat': 'Sluit het spel',
          'oyunaDön': 'Terug naar Spel',
          'sari': 'Geel',
          'kirmizi': 'Rood',
          'mavi': 'Blauw',
          'yesil': 'Groen',
          'mor': 'Paars',
          "Kazandınız": "Je hebt gewonnen",
          "Speed": "Snelheid",
          "Swipe": "Omhoog vegen"
        },
        'nn_NO': {
          'puan': 'Pens: ',
          'oyna': 'Skuespill',
          'zamanbitti': 'Tidsavbrudd',
          'reklamMetni': 'Tjen +11 sekunder ved å se belønningsannonser.',
          'reklamButonu': 'Vis annonser',
          'tekrarOyna': 'Spill på nytt',
          'dildeğiştir': 'Norway',
          'oyunuKapat': 'Lukk spillet',
          'oyunaDön': 'Tilbake til spillet',
          'sari': 'Gul',
          'kirmizi': 'Rød',
          'mavi': 'Blå',
          'yesil': 'Grønn',
          'mor': 'Lilla',
          "Kazandınız": "Du vant",
          "Speed": "Fart",
          "Swipe": "Sveip opp"
        },
        'fr_FR': {
          'puan': 'Scoren: ',
          'oyna': 'J O U E R',
          'zamanbitti': 'Le Temps Est écoulé',
          'reklamMetni': 'Gagnez +11 secondes en regardant des publicités avec récompense.',
          'reklamButonu': 'Voir les annonces',
          'tekrarOyna': 'Rejouer',
          'dildeğiştir': 'French',
          'oyunuKapat': 'Fermer le jeu',
          'oyunaDön': 'Retour au jeu',
          'sari': 'Jaune',
          'kirmizi': 'Rouge',
          'mavi': 'Bleu',
          'yesil': 'Vert',
          'mor': 'Pourpre',
          "Kazandınız": "Vous avez gagné",
          "Speed": "Vitesse",
          "Swipe": "Balayez vers le haut",
        },
        'fr_LU': {
          'puan': 'Scoren: ',
          'oyna': 'J O U E R',
          'zamanbitti': 'Le Temps Est écoulé',
          'reklamMetni': 'Gagnez +11 secondes en regardant des publicités avec récompense.',
          'reklamButonu': 'Voir les annonces',
          'tekrarOyna': 'Rejouer',
          'dildeğiştir': 'French',
          'oyunuKapat': 'Fermer le jeu',
          'oyunaDön': 'Retour au jeu',
          'sari': 'Jaune',
          'kirmizi': 'Rouge',
          'mavi': 'Bleu',
          'yesil': 'Vert',
          'mor': 'Pourpre',
          "Kazandınız": "Vous avez gagné",
          "Speed": "Vitesse",
          "Swipe": "Balayez vers le haut",
        },
        'fr_MC': {
          'puan': 'Scoren: ',
          'oyna': 'J O U E R',
          'zamanbitti': 'Le Temps Est écoulé',
          'reklamMetni': 'Gagnez +11 secondes en regardant des publicités avec récompense.',
          'reklamButonu': 'Voir les annonces',
          'tekrarOyna': 'Rejouer',
          'dildeğiştir': 'French',
          'oyunuKapat': 'Fermer le jeu',
          'oyunaDön': 'Retour au jeu',
          'sari': 'Jaune',
          'kirmizi': 'Rouge',
          'mavi': 'Bleu',
          'yesil': 'Vert',
          'mor': 'Pourpre',
          "Kazandınız": "Vous avez gagné",
          "Speed": "Vitesse",
          "Swipe": "Balayez vers le haut",
        },
        'fr_CH': {
          'puan': 'Scoren: ',
          'oyna': 'J O U E R',
          'zamanbitti': 'Le Temps Est écoulé',
          'reklamMetni': 'Gagnez +11 secondes en regardant des publicités avec récompense.',
          'reklamButonu': 'Voir les annonces',
          'tekrarOyna': 'Rejouer',
          'dildeğiştir': 'French',
          'oyunuKapat': 'Fermer le jeu',
          'oyunaDön': 'Retour au jeu',
          'sari': 'Jaune',
          'kirmizi': 'Rouge',
          'mavi': 'Bleu',
          'yesil': 'Vert',
          'mor': 'Pourpre',
          "Kazandınız": "Vous avez gagné",
          "Speed": "Vitesse",
          "Swipe": "Balayez vers le haut",
        },
        'ru_RU': {
          'puan': 'точка: ',
          'oyna': 'Начинать',
          'zamanbitti': 'время истекло',
          'reklamMetni': 'Заработайте +11 секунд, просматривая рекламу с вознаграждением.',
          'reklamButonu': 'смотреть рекламу',
          'tekrarOyna': 'играть снова',
          'dildeğiştir': 'Russian',
          'oyunuKapat': 'Закрыть игру',
          'oyunaDön': 'Вернуться к игре',
          'sari': 'Жёлтый',
          'kirmizi': 'Красный',
          'mavi': 'Синий',
          'yesil': 'Зеленый',
          'mor': 'Пурпурный',
          "Kazandınız": "Вы выиграли",
          "Speed": "Скорость",
          "Swipe": "Проведите пальцем вверх",
        },
        'es_ES': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_VE': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_UY': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_PE': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_PR': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_PY': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_MX': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_HN': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_GT': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_SV': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_EC': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_DO': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_CR': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_CO': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_CL': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_BO': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'es_AR': {
          'puan': 'Puntaje: ',
          'oyna': 'Empezar',
          'zamanbitti': 'El tiempo ha expirado',
          'reklamMetni': 'Gane +11 segundos al ver Anuncios Recompensados.',
          'reklamButonu': 'Ver anuncios',
          'tekrarOyna': 'Juega de Nuevo',
          'dildeğiştir': 'Spanish',
          'oyunuKapat': 'Cerrar el juego',
          'oyunaDön': 'Volver al juego',
          'sari': 'Amarillo',
          'kirmizi': 'Rojo',
          'mavi': 'Azul',
          'yesil': 'Verde',
          'mor': 'Morado',
          "Kazandınız": "Ganaste",
          "Speed": "Velocidad",
          "Swipe": "Desliza el dedo hacia arriba",
        },
        'ja_JP': {
          'puan': 'スコア : ',
          'oyna': '始める',
          'zamanbitti': 'たんま',
          'reklamMetni': 'リワード広告を表示すると +11 秒増加します。',
          'reklamButonu': 'お知らせを表示する',
          'tekrarOyna': 'もう一度再生',
          'dildeğiştir': 'Japanese',
          'oyunuKapat': 'ゲームを閉じる',
          'oyunaDön': 'ゲームに戻る',
          'sari': '黄色',
          'kirmizi': '赤い',
          'mavi': '青い',
          'yesil': '緑',
          'mor': '紫',
          "Kazandınız": "あなたが勝った",
          "Speed": "速度",
          "Swipe": "上にスワイプ",
        },
      };
}
