// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoWujRbLL2iGyLdJoN8QHTjvgz55_dBzk',
    appId: '1:1001866780856:web:2d8ca866f200728f86144d',
    messagingSenderId: '1001866780856',
    projectId: 'unic-otantic-e4f32',
    authDomain: 'unic-otantic-e4f32.firebaseapp.com',
    databaseURL: 'https://unic-otantic-e4f32-default-rtdb.firebaseio.com',
    storageBucket: 'unic-otantic-e4f32.appspot.com',
    measurementId: 'G-J8PW23J36R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbW7zta7H-Rd0OFm72MY4NdH9jBF8H2UQ',
    appId: '1:1001866780856:android:b2ff9782a646740d86144d',
    messagingSenderId: '1001866780856',
    projectId: 'unic-otantic-e4f32',
    databaseURL: 'https://unic-otantic-e4f32-default-rtdb.firebaseio.com',
    storageBucket: 'unic-otantic-e4f32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLgQslKUDXsbJtIeN3eWJCfEj2javCdyA',
    appId: '1:1001866780856:ios:23428eef258626a086144d',
    messagingSenderId: '1001866780856',
    projectId: 'unic-otantic-e4f32',
    databaseURL: 'https://unic-otantic-e4f32-default-rtdb.firebaseio.com',
    storageBucket: 'unic-otantic-e4f32.appspot.com',
    androidClientId: '1001866780856-71r1098rum85ifbvorb7b0am4daf8rec.apps.googleusercontent.com',
    iosClientId: '1001866780856-cmmivolbq77i4p0bt8dmi7ee3pb1tu3q.apps.googleusercontent.com',
    iosBundleId: 'com.unicotantic.unicotantic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLgQslKUDXsbJtIeN3eWJCfEj2javCdyA',
    appId: '1:1001866780856:ios:23428eef258626a086144d',
    messagingSenderId: '1001866780856',
    projectId: 'unic-otantic-e4f32',
    databaseURL: 'https://unic-otantic-e4f32-default-rtdb.firebaseio.com',
    storageBucket: 'unic-otantic-e4f32.appspot.com',
    androidClientId: '1001866780856-71r1098rum85ifbvorb7b0am4daf8rec.apps.googleusercontent.com',
    iosClientId: '1001866780856-cmmivolbq77i4p0bt8dmi7ee3pb1tu3q.apps.googleusercontent.com',
    iosBundleId: 'com.unicotantic.unicotantic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoWujRbLL2iGyLdJoN8QHTjvgz55_dBzk',
    appId: '1:1001866780856:web:2d8ca866f200728f86144d',
    messagingSenderId: '1001866780856',
    projectId: 'unic-otantic-e4f32',
    authDomain: 'unic-otantic-e4f32.firebaseapp.com',
    databaseURL: 'https://unic-otantic-e4f32-default-rtdb.firebaseio.com',
    storageBucket: 'unic-otantic-e4f32.appspot.com',
    measurementId: 'G-J8PW23J36R',
  );

}